---
title: "Supplemental Figure 3"
author: "Abby"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    dev: png
---

Supplemental Figure 3: Microbiome compositional differences at baseline and post MCT/EVOO.

Show all samples colored by Bacteroides and prevotella.



```{r setup, include=FALSE, message = FALSE}
# this chunck sets up the rmd document

require(rmarkdown)
require(knitr)
require(tidyverse)
require(RColorBrewer) 
require(cowplot)
require(reshape2)
require(ggdendro)
require(vegan)
require(ape)

# set the path for root directory
opts_knit$set(root.dir = "/Users/abby/Documents/Projects/dietstudy/")

# create a directory for the figure and set it's resolution/format
opts_chunk$set(echo = TRUE, fig.path = "Figs/", dev = c("png", "pdf"), dpi = 300)

# set up colors
evoomctpal <- c("#e66101", "#5e3c99")

```

```{r load_maps, echo = FALSE}
#### load the maps for downstream use ####
map_sample <- read.table("data/maps/SampleID_map.txt", sep = "\t", header = T, comment = "")
map_username <- read.table("data/maps/UserName_map.txt", sep = "\t", header = T, comment = "")
map_sample$StudyDate <- as.Date.factor(map_sample$StudyDate, format = "%m/%d/%y")

#load other maps
food_map <- read.table("data/maps/food_map.txt", sep = "\t", header = T, comment = "")
tax_map <- read.table("data/maps/taxonomy_norm_map.txt", sep = "\t", header = T, comment = "")

```

```{r all_tax, echo = F, include = F, fig.height = 1.5, fig.width =1.5}

tax_all <- read.delim("data/processed_tax/taxonomy_clr_s.txt", row = 1)

pre <- map_sample[map_sample$Timing == "Pre",]$X.SampleID
post <- map_sample[map_sample$Timing == "Post",]$X.SampleID

tax_pre <- tax_all[colnames(tax_all) %in% pre]
tax_post <- tax_all[colnames(tax_all) %in% post]

#make dist matrix
tax_all_dist <- dist(t(tax_all))
tax_pre_dist <- dist(t(tax_pre))
tax_post_dist <- dist(t(tax_post))

# make pcoa
tax_all_pcoa <- data.frame(pcoa(tax_all_dist)$vectors)
tax_pre_pcoa <- data.frame(pcoa(tax_pre_dist)$vectors)
tax_post_pcoa <- data.frame(pcoa(tax_post_dist)$vectors)

eigen <- pcoa(tax_all_dist)$values$Eigenvalues
eigen_pre <- pcoa(tax_pre_dist)$values$Eigenvalues
eigen_post <- pcoa(tax_post_dist)$values$Eigenvalues

percent_var <- signif(eigen/sum(eigen), 4)*100
percent_var_pre <- signif(eigen_pre/sum(eigen_pre), 4)*100
percent_var_post <- signif(eigen_post/sum(eigen_post), 4)*100



### MAKE ALL ####
# move rownames to a column
tax_all_pcoa <- rownames_to_column(tax_all_pcoa, var = "X.SampleID")

#merge map and PCOA by SampleID - select both lines and run together - won't work otherwise
tax_all_pcoa <- inner_join(tax_all_pcoa, map_sample, by = 'X.SampleID')

tax_all_pcoa$UserName <- gsub(pattern = "MCTs", "", tax_all_pcoa$UserName)

tax_all_plot <- ggplot(tax_all_pcoa, aes(x = Axis.1, y = Axis.2)) +
  geom_point(aes(color = Supplement), alpha=0.75, size = 2, alpha = 0.1) +
  stat_ellipse(aes(color = Supplement), type = "norm", linetype = 2, level = 0.95, alpha = 0.7) +
  scale_color_manual(values = evoomctpal) +
  xlab(paste0("PC 1 [",percent_var[1],"%]")) +
  ylab(paste0("PC 2 [",percent_var[2],"%]")) +
  theme_classic() +                                                                      
    theme(legend.position = "none",
        legend.title.align = 0.5,
        legend.text = element_text(size = 9),
        axis.text = element_text(size = 4),
        axis.title = element_text(size = 9)) +
  guides(color = guide_legend(ncol = 1)) 

tax_all_plot



### MAKE PRE ###
# move rownames to a column
tax_pre_pcoa <- rownames_to_column(tax_pre_pcoa, var = "X.SampleID")

#merge map and PCOA by SampleID - select both lines and run together - won't work otherwise
tax_pre_pcoa <- inner_join(tax_pre_pcoa, map_sample, by = 'X.SampleID')

#test significance
# test for plotting pvalue
tax_pre_sort <- as.data.frame(t(tax_pre))
tax_pre_sort <- rownames_to_column(tax_pre_sort, var = "X.SampleID")
tax_pre_sort <- inner_join(tax_pre_sort, map_sample, by = "X.SampleID")

mytest <- adonis(tax_pre_dist~tax_pre_sort$Supplement, permutations = 999)
plot_p <- mytest$aov.tab$`Pr(>F)`[1]

tax_pre_pcoa$UserName <- gsub(pattern = "MCTs", "", tax_pre_pcoa$UserName)

tax_pre_plot <- ggplot(tax_pre_pcoa, aes(x = Axis.1, y = Axis.2)) +
  geom_point(aes(color = Supplement), alpha=0.75, size = 2, alpha = 0.1) +
  stat_ellipse(aes(color = Supplement), type = "norm", linetype = 2, level = 0.95, alpha = 0.7) +
  scale_color_manual(values = evoomctpal) +
  xlab(paste0("PC 1 [",percent_var_pre[1],"%]")) +
  ylab(paste0("PC 2 [",percent_var_pre[2],"%]")) +
  theme_classic() +                                                                      
    theme(legend.position = "none",
        legend.title.align = 0.5,
        legend.text = element_text(size = 9),
        axis.text = element_text(size = 4),
        axis.title = element_text(size = 9)) +
  guides(color = guide_legend(ncol = 1)) +
  annotate("text", x = 0, y = -25, label = paste0("p-value = ",plot_p), size=2)

tax_pre_plot




### MAKE POST ###
# move rownames to a column
tax_post_pcoa <- rownames_to_column(tax_post_pcoa, var = "X.SampleID")

#merge map and PCOA by SampleID - select both lines and run together - won't work otherwise
tax_post_pcoa <- inner_join(tax_post_pcoa, map_sample, by = 'X.SampleID')

# test for plotting pvalue
tax_post_sort <- as.data.frame(t(tax_post))
tax_post_sort <- rownames_to_column(tax_post_sort, var = "X.SampleID")
tax_post_sort <- inner_join(tax_post_sort, map_sample, by = "X.SampleID")

mytest <- adonis(tax_post_dist~tax_post_sort$Supplement, permutations = 999)
plot_p <- mytest$aov.tab$`Pr(>F)`[1]

tax_post_pcoa$UserName <- gsub(pattern = "MCTs", "", tax_post_pcoa$UserName)

tax_post_plot <- ggplot(tax_post_pcoa, aes(x = Axis.1, y = Axis.2)) +
  geom_point(aes(color = Supplement), alpha=0.75, size = 2, alpha = 0.1) +
  stat_ellipse(aes(color = Supplement), type = "norm", linetype = 2, level = 0.95, alpha = 0.7) +
  scale_color_manual(values = evoomctpal) +
  xlab(paste0("PC 1 [",percent_var_post[1],"%]")) +
  ylab(paste0("PC 2 [",percent_var_post[2],"%]")) +
  theme_classic() +                                                                      
    theme(legend.position = "none",
        legend.title.align = 0.5,
        legend.text = element_text(size = 9),
        axis.text = element_text(size = 4),
        axis.title = element_text(size = 9)) +
  guides(color = guide_legend(ncol = 1)) +
  annotate("text", x = -7, y = -27, label = paste0("p-value = ",plot_p), size=2)


tax_post_plot



```

```{r, phyla_colored, echo = F, include = F, fig.height = 4}
colpal<- colorRampPalette(brewer.pal(11,"Spectral"))(15) #spectral progression
colpal <- rev(colpal)

tax_all_g <- read.delim("data/processed_tax/taxonomy_norm_g.txt", row = 1)
tax_all_g = tax_all_g[order(rowMeans(tax_all_g),decreasing=T),]

#selet top four
tax_all_g <- tax_all_g[1:4,]
#traspose to add to map for later use
tax_all_g <- t(tax_all_g)
#colnames(sptaxa) <- gsub("^.*\\.","", colnames(sptaxa) )
colnames(tax_all_g) <- gsub(".*;g__?", "", colnames(tax_all_g))
colnames(tax_all_g) <- gsub("_", "", colnames(tax_all_g))
colnames(tax_all_g) <- gsub(";.*","",colnames(tax_all_g))

myrownames <- rownames(tax_all_g)

tax_all_g <- apply(tax_all_g, 2, function(x) cut(x, breaks = seq(0, max(x), length.out = 15), dig.lab = 2))

rownames(tax_all_g) <- myrownames

tax_all_g <- as.data.frame(tax_all_g)
tax_all_g <- rownames_to_column(tax_all_g, "X.SampleID")

# add realative abundace of species taxa to the map for plotting
map_sample <- left_join(map_sample,tax_all_g, by = "X.SampleID")

### make the plot ###

tax_all <- read.delim("data/processed_tax/taxonomy_clr_s.txt", row = 1)
tax_all_dist <- dist(t(tax_all))
tax_all_pcoa <- data.frame(pcoa(tax_all_dist)$vectors)

eigen <- pcoa(tax_all_dist)$values$Eigenvalues

percent_var <- signif(eigen/sum(eigen), 4)*100

### MAKE ALL ####
# move rownames to a column
tax_all_pcoa <- rownames_to_column(tax_all_pcoa, var = "X.SampleID")

#merge map and PCOA by SampleID - select both lines and run together - won't work otherwise
tax_all_pcoa <- inner_join(tax_all_pcoa, map_sample, by = 'X.SampleID')

tax_all_pcoa$UserName <- gsub(pattern = "MCTs", "", tax_all_pcoa$UserName)


tax_all_prev <- ggplot(tax_all_pcoa, aes(x = Axis.1, y = Axis.2)) +
  geom_point(aes(color = Prevotella), size = 2, alpha = 0.75) +
  stat_ellipse(aes(color = Supplement), type = "norm", linetype = 2, level = 0.95, alpha = 0.3) +
  scale_color_manual(values = c(colpal, rev(evoomctpal))) +
  xlab(paste0("PC 1 [",percent_var[1],"%]")) +
  ylab(paste0("PC 2 [",percent_var[2],"%]")) +
  theme_classic() +                                                                      
    theme(legend.position = "bottom",
        legend.title.align = 0.5,
        legend.title = element_text(size = 9),
        legend.text = element_text(size = 4),
        axis.text = element_text(size = 4),
        axis.title = element_text(size = 9),
        aspect.ratio = 1) +
  guides(color = guide_legend(nrow = 6, title.position = "top"))
 
tax_all_prev


tax_all_bact <- ggplot(tax_all_pcoa, aes(x = Axis.1, y = Axis.2)) +
  geom_point(aes(color = Bacteroides), size = 2, alpha = 0.75) +
  stat_ellipse(aes(color = Supplement), type = "norm", linetype = 2, level = 0.95, alpha = 0.3) +
  scale_color_manual(values = c(colpal, rev(evoomctpal))) +
  xlab(paste0("PC 1 [",percent_var[1],"%]")) +
  ylab(paste0("PC 2 [",percent_var[2],"%]")) +
  theme_classic() +                                                                      
    theme(legend.position = "bottom",
        legend.title.align = 0.5,
        legend.title = element_text(size = 9),
        legend.text = element_text(size = 4),
        axis.text = element_text(size = 4),
        axis.title = element_text(size = 9),
        aspect.ratio = 1) +
  guides(color = guide_legend(nrow = 6, title.position = "top"))



tax_all_bact


```