---
title: "PCOA akronymer"
author: "Abby"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE, message = FALSE}

require(rmarkdown)
require(knitr)
require(RColorBrewer) 
require(tidyverse)
require(ape)
require(vegan)
require(cowplot)

opts_knit$set(root.dir = "/Users/abby/Documents/Projects/dietstudy/")
opts_chunk$set(echo = TRUE, fig.path = "Figs/", dev = c("png", "pdf"), dpi = 300)

```

```{r load long map, echo = FALSE}
map <- read.table("data/maps/SampleID_map.txt", sep = "\t", header = T, comment = "")
map_username <- read.table("data/maps/UserName_map.txt", sep = "\t", header = T, comment = "")


source(file = "lib/UserNameColors.R")




```


```{r import beta div, include =F, message = F}

#akronymer distances
div <- read.delim("data/akronymer/AllRf.dm.txt", sep = "\t", row.names = 1)

div <- div[rownames(div) %in% map$X.SampleID, colnames(div) %in% map$X.SampleID]

div_d <- as.dist(div)

rownames(map) <- map$X.SampleID
map_ord <- map[rownames(div),]


#bray distances
div2 <- read.delim("data/processed_tax/taxonomy_norm_s.txt", sep = "\t", row.names = 1)
div2 <- div2[,colnames(div2) %in% map$X.SampleID]



div2_d <- vegdist(t(div2), method = "bray")


```

Make the pcoa plot

```{r pcoa, echo = F, fig.width=5, fig.height=2.5}

names(UserNameColors) <- gsub("MCTs", "", names(UserNameColors)) 

#betad as matrix 
plot <- data.frame(pcoa(div_d)$vectors)

# move rownames to a column
plot <- rownames_to_column(plot, var = "X.SampleID")


#merge map and PCOA by SampleID - select both lines and run together - won't work otherwise
plot <- inner_join(plot, map, by = 'X.SampleID')
plot$UserName <- gsub("MCTs", "", plot$UserName)


PCA_12_ak <-ggplot(plot, aes(x = Axis.1, y = Axis.2)) +
  geom_point(aes(color = as.factor(plot$UserName)), alpha=0.7, size = 3) +
  scale_color_manual(values = UserNameColors) +
  #scale_color_manual(values = c("black", "dark grey")) +
  #scale_shape_manual(values = shape_pal3) +
  stat_ellipse(aes(group = UserName, color = UserName), linetype = 2, level = 0.95) +
  #labs(title="Akronymer PCOA colored by Subject") +
  coord_fixed(ratio = 1)+
   guides(color = guide_legend(ncol = 4)) +
  theme_classic(base_family = "Helvetica") +                                                                      
  theme(plot.title = element_text(size = 14, hjust = 0.5),
        legend.position = "right",
        legend.title = element_blank()) 
  

PCA_12_ak

#betad as matrix 
plot2 <- data.frame(pcoa(div2_d)$vectors)

# move rownames to a column
plot2 <- rownames_to_column(plot2, var = "X.SampleID")


#merge map and PCOA by SampleID - select both lines and run together - won't work otherwise
plot2 <- inner_join(plot2, map, by = 'X.SampleID')
plot2$UserName <- gsub("MCTs", "", plot2$UserName)

PCA_12_bray <-ggplot(plot2, aes(x = Axis.1, y = Axis.2)) +
  geom_point(aes(color = as.factor(plot2$UserName)), alpha=0.7, size = 3) +
  scale_color_manual(values = UserNameColors) +
  #scale_color_manual(values = c("black", "dark grey")) +
  #scale_shape_manual(values = shape_pal3) +
  stat_ellipse(aes(group = UserName, color = UserName), linetype = 2, level = 0.95) +
  #labs(title="Akronymer PCOA colored by Subject") +
  guides(color = guide_legend(ncol = 4)) +
  theme_classic(base_family = "Helvetica") +                                                                      
  theme(plot.title = element_text(size = 14, hjust = 0.5),
        legend.position = "right",
        legend.title = element_blank())


#plot_grid(PCA_12_ak, PCA_12_bray, rel_widths = c(1,2))




```





```{r}


adonis(div_d~map_ord$UserName + map_ord$UserName, permutations = 999)


```








