---
title: "Microbiome visualization"
author: "Abby"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

Visualizing microbimoe composition for all subjects.

```{r setup, include=FALSE, message = FALSE}

require(rmarkdown)
require(knitr)
require(tidyverse)
require(stringr)
require(RColorBrewer) 
require(cowplot)
require(reshape2)
require(ggdendro)
require(vegan)


opts_knit$set(root.dir = "/Users/abby/Documents/Projects/dietstudy/")
opts_chunk$set(echo = TRUE, fig.path = "Figs/", dev = c("png", "pdf"), dpi = 300)

```

```{r load long map, echo = FALSE}
map <- read.table("data/maps/SampleID_map.txt", sep = "\t", header = T, comment = "")
map_username <- read.table("data/maps/UserName_map.txt", sep = "\t", header = T, comment = "")
tax_map <- read.table("data/maps/taxonomy_norm_map.txt", sep = "\t", header = T, comment = "")

# set up colors
cols <- brewer.pal(12, "Set3")
cols2 <- colorRampPalette(cols)

# get the order of usernames for plotting
#order <- read.table("data/processed_tax/taxa_alpha.txt", header = T, sep ="\t", comment = "")
#colnames(order)[1] <- "X.SampleID"
#order <- inner_join(order, map, by = "X.SampleID")
#order <- order %>% group_by(UserName) %>% dplyr::summarize(mean(chao1))
#order <- order[order(order$`mean(chao1)`, decreasing = T),]
#ord_factor <- as.character(order$UserName)

# load order determined by clustering average microbiome
ord_factor <- load(file = "data/order_by_similaritiy.rdata")
ord_factor <- sim.order
```

```{r load microbiome species taxa table, echo = FALSE}

# import averages per person for clustering
microbes <- read.delim("data/processed_UN_tax/UN_taxonomy_norm_s.txt", row = 1)

# cluster based on the the sqrt relative abundance - since that's what we are displaying in the figure
microbes.sq <- sweep(sqrt(microbes), 2, colSums(sqrt(microbes)), "/")
colSums(microbes.sq)

```

```{r order, echo = F, fig.width = 15.5, fig.height=4}

mydist <- vegdist(t(microbes.sq), method = "bray") # should update this to what ever method I end up using in the paper (bray for clr, but should use a tree method with relative abundance data)
myclust <- hclust(mydist, method = "average")
order <- myclust$order
microbes <- microbes[,order]
sim.order <- as.character(colnames(microbes))
save(sim.order, file = "data/order_by_similaritiy.RData")

#myclust$labels <- gsub("MCTs", "", myclust$labels)

dend <- as.dendrogram(myclust)
ddata <- dendro_data(dend, type = "rectangle")

labs <- label(ddata)
labs <- inner_join(labs, map_username, by = c("label"="UserName" ))
labs$label <- gsub("MCTs", "", labs$label)

dend_plot <- ggplot(segment(ddata)) + 
  geom_segment(aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_text(data=labs, aes(label=label, x =x, y =0, 
                           color = labs$Race.Ethnicity, 
                           angle = 0, hjust = 0.5, vjust = 1)) +
  theme_dendro() +
  theme(legend.position = "none", legend.title = element_blank())
  
dend_plot  

```



```{r import microbiome and reshape for plotting, include =F, message = F}
# import microbiome data
taxa <- read.table("data/processed_tax/taxonomy_norm_s.txt", header = T, row.names = 1, sep = "\t", comment = "")

# collapse at level 3
# Summarizing at different levels - makes changes to everything downstream
split <- strsplit(rownames(taxa),";")             # Split and rejoin on lv7 to get species level
taxaStrings <- sapply(split,function(x) paste(x[1:7],collapse=";"))
taxa<- rowsum(taxa,taxaStrings)              # Collapse by taxonomy name

# for plotting, limit to top ~20 bugs
taxa = taxa[rowMeans(taxa) >= 0.007,]

#readjust for plotting
taxa = sweep(sqrt(taxa),2,colSums(sqrt(taxa)),'/')

# convert to relative abundance
#taxa <- sweep(taxa, 2, colSums(taxa), "/")

# sort by highest average relative abundance
taxa <- taxa[order(rowMeans(taxa), decreasing = T),]

# make tax ordering factor
tax_ord_factor <- as.character(rownames(taxa))

plot <- as.data.frame(t(taxa))
plot <- rownames_to_column(plot, var = "X.SampleID")
plot <- melt(plot, id = "X.SampleID", variable.name = "Species")

# label low abundance foods as "<x% abundance"
# plot$Species <- as.character(plot$Species) #convert to character
# plot$Species[plot$value < 0.04] <- "Other" #rename genera with < 2.5% abundance

# combine all "<x% abundance" foods into one for plotting
plot <- plot %>% group_by(X.SampleID, Species) %>% dplyr::summarise(newvalue = sum(value))

# fix labeling for plotting
plot$Species<- gsub("?.*s__", " ", plot$Species)
plot$Species <- gsub("_", " ", plot$Species)

# merge with map to get day variable
plot <- merge(plot, map, by = "X.SampleID")

```


```{r microbiome_subject_day_wide, echo = F, fig.height=4, fig.width=15.5}
set.seed(11)

# get right number of colors for plotting
no_cols <- length(unique(plot$Species))
colors <- sample(cols2(no_cols))

# order participants by their microbiome diversity
# reorder by ordered factor
plot$UserName <- gsub("MCTs", "", plot$UserName)
ord_factor <- gsub("MCTs", "", ord_factor)
plot$UserName <- factor(plot$UserName, levels = ord_factor)

# reorder food species
tax_ord_factor <- gsub("?.*s__", " ", tax_ord_factor)
tax_ord_factor <- gsub("_", " ", tax_ord_factor)
plot$Species <- as.factor(plot$Species)
plot$Species <-factor(plot$Species, levels = tax_ord_factor)

# make the plot
myplot <- ggplot(plot, aes(x = StudyDayNo, y = newvalue, fill = Species)) +
 #facet_grid(UserName~.) +
  facet_grid(.~UserName) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = colors) +
  scale_x_discrete(drop = FALSE) +
  theme_classic() +
  theme(strip.text.x = element_text(angle = 0, size = 7, face = "italic"),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(size = 3),
        axis.title = element_text(size = 7),
        plot.title = element_text(hjust = 0.5),
        axis.title.x = element_blank(),
        strip.background = element_rect(color = "grey"), 
        legend.position = "bottom",
        legend.title = element_blank()) +
  guides(fill = guide_legend(reverse = FALSE, 
                             keywidth = 0.5, 
                             keyheight = 0.5, 
                             nrow = 3)) +
  ylab("sqrt(Relative Abundance)\n") 
  #xlab("Study Day") +
  #ggtitle("Microbiome Composition of Subjects by Day - ordered by average microbiome similarity")
```

```{r cowplot, echo = F, fig.width=16, fig.height = 7}

plot_grid(dend_plot, myplot, ncol = 1, scale = c(1,.95), rel_heights = c(1, 1.4))

```
