---
title: "Figure 4"
author: "Abby"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    dev: png
---

Figure 4: Will show the beta diversity plots for microbiome, diet, and function and the procrustes between diet and microbiome, diet and nutrients, and diet and function.




```{r setup, include=FALSE, message = FALSE}
# this chunck sets up the rmd document

require(rmarkdown)
require(knitr)
require(tidyverse)
require(RColorBrewer) 
require(cowplot)
require(reshape2)
require(ggdendro)
require(vegan)
require(ape)

# set the path for root directory
opts_knit$set(root.dir = "/Users/abby/Documents/Projects/dietstudy/")

# create a directory for the figure and set it's resolution/format
opts_chunk$set(echo = TRUE, fig.path = "Figs/", dev = c("png", "pdf"), dpi = 300)


# set up colors
pal <- c("#ff0000", "#ffd940", "#008c4b", "#00138c", "#8c235b", "#ffbfbf", "#8c7723", "#468c75", "#8091ff", "#ff80c4", "#8c3123", "#fff2bf", "#40fff2", "#69698c", "#ff0044", "#ff9180", "#e5ff80", "#bffbff", "#5940ff", "#8c696e", "#8c7369", "#858c69", "#40d9ff", "#c480ff", "#ff8c40", "#4b8c00", "#23698c", "#69238c", "#8c4b00", "#bfffbf", "#004b8c", "#eabfff", "#ffc480", "#40ff59", "#80c4ff", "#ff40f2")
pal1 <- c("#ff0015", "#0073ff", "#adffcb", "#8c0000", "#ffadb4", "#add2ff", "#5f8c70", "#8c5f5f", "#bb00ff", "#5f748c", "#d0ff00", "#67008c", "#00ff5e", "#738c00", "#e9adff", "#008c33", "#f0ffad")
pal2 <- c("#8c5f63", "#ff0015", "#e9adff", "#003f8c", "#0073ff", "#adffcb", "#738c00", "#d0ff00", "#8c000c", "#67008c", "#bb00ff", "#add2ff", "#008c33", "#00ff5e", "#f0ffad", "#ffadad")
pal3 <- c("#ff4066", "#8091ff", "#c3ffbf", "#7a5c62", "#bfc8ff", "#7a771f", "#df40ff", "#40ffec", "#fffb80", "#703d7a", "#3d7a74", "#ff0000", "#f4bfff", "#bffff9", "#7a1f1f", "#00107a", "#11ff00", "#ffbfbf", "#4059ff", "#417a3d")

set.seed(42)
```

```{r load data, echo = FALSE}
#### load the maps for downstream use ####
map_sample <- read.table("data/maps/SampleID_map.txt", sep = "\t", header = T, comment = "")
map_username <- read.table("data/maps/UserName_map.txt", sep = "\t", header = T, comment = "")
map_sample$StudyDate <- as.Date.factor(map_sample$StudyDate, format = "%m/%d/%y")

#load other maps
food_map <- read.table("data/maps/food_map.txt", sep = "\t", header = T, comment = "")
tax_map <- read.table("data/maps/taxonomy_norm_map.txt", sep = "\t", header = T, comment = "")


##########food##############
# load the food distance matrix, unweighted unifrac
food_un <- read.delim("data/processed_food/dhydrt_smry_no_soy_beta/unweighted_unifrac_dhydrt.smry.no.soy.txt", row = 1) # weighted in not significant
food_dist <- as.dist(food_un)

# make non-tree distance matrix for food (for supplemental)
food <- read.delim("data/processed_food/dhydrt.smry.no.soy.txt", row = 1)
food <- food[,colnames(food) %in% colnames(food_un)]
no_tree_dist <- dist(t(food))


##############taxonomy############
# load taxonomy collapsed for each person
tax <- read.delim("data/processed_UN_tax/UN_taxonomy_clr_s.txt", row = 1)
# drop soylents
tax <- tax[,colnames(tax) %in% colnames(food_un)]

# make taxonomy distance matrix
tax_dist <- dist(t(tax))


###############nutrients############
# load nutrition data
nutr <- read.delim("data/processed_nutr/nutr_65_smry_no_soy.txt", row = 1)

# normalize nutrition data across features (rows)
nutr_n <- sweep(nutr, 1, rowSums(nutr), "/")

# make nutrition distance matrix (euclidean)
nutr_dist <- dist(t(nutr_n))


##############function################
# load function data
func <- read.delim("data/processed_KEGG/ave_KEGG_modules_no_soy.txt", row = 1)

# make funciton distance matrix (euclidean)
func_dist <- dist(t(func))


```

```{r all_food, echo = F, include = F, fig.height = 4, fig.width =6}
# identify soylent samples
soylent <- map_sample[map_sample$UserName %in% c("MCTs11", "MCTs12"),]
soylent <- as.character(soylent$X.SampleID)

food_all <- read.delim("data/processed_food/dhydrt_beta/unweighted_unifrac_dhydrt.txt", row = 1)

# drop soylent 
food_all_ns <- food_all[!rownames(food_all) %in% soylent, !colnames(food_all) %in% soylent]

food_all_pcoa <- data.frame(pcoa(food_all_ns)$vectors)

eigen <- pcoa(food_all_ns)$values$Eigenvalues

percent_var <- signif(eigen/sum(eigen), 4)*100

# move rownames to a column
food_all_pcoa <- rownames_to_column(food_all_pcoa, var = "X.SampleID")

#merge map and PCOA by SampleID - select both lines and run together - won't work otherwise
food_all_pcoa <- inner_join(food_all_pcoa, map_sample, by = 'X.SampleID')

food_all_pcoa$UserName <- gsub(pattern = "MCTs", "", food_all_pcoa$UserName)

food_all_plot <- ggplot(food_all_pcoa, aes(x = Axis.1, y = Axis.2, fill = UserName)) +
  geom_point(color = "black", alpha=0.75, pch = 21, size = 2, alpha = 0.5) +
  #geom_line(aes(color = UserName)) +
  stat_ellipse(aes(color = UserName), type = "norm", linetype = 2, level = 0.95, alpha = 0.3) +
  scale_fill_manual(name = "Subject", values = pal) + 
  scale_color_manual(values = pal) +
  xlab(paste0("PCOA 1 [",percent_var[1],"%]")) +
  ylab(paste0("PCOA 2 [",percent_var[2],"%]")) +
  theme_classic() +                                                                      
  theme(legend.position = "right",
        legend.title.align = 0.5,
        legend.text = element_text(size = 9),
        axis.text = element_text(size = 9)) +
  guides(color = F, fill = guide_legend(ncol = 4)) 
  #theme(legend.title = element_text("Subject"))

food_all_plot

```

```{r all_tax, echo = F, include = F, fig.height = 4, fig.width =4}

tax_all <- read.delim("data/processed_tax/taxonomy_clr_s.txt", row = 1)

# drop soylent 
tax_all_ns <- tax_all[, !colnames(tax_all) %in% soylent]

#make dist matrix
tax_all_dist <- dist(t(tax_all_ns))

# make pcoa
tax_all_pcoa <- data.frame(pcoa(tax_all_dist)$vectors)

eigen <- pcoa(tax_all_dist)$values$Eigenvalues

percent_var <- signif(eigen/sum(eigen), 4)*100

# move rownames to a column
tax_all_pcoa <- rownames_to_column(tax_all_pcoa, var = "X.SampleID")

#merge map and PCOA by SampleID - select both lines and run together - won't work otherwise
tax_all_pcoa <- inner_join(tax_all_pcoa, map_sample, by = 'X.SampleID')

tax_all_pcoa$UserName <- gsub(pattern = "MCTs", "", tax_all_pcoa$UserName)

tax_all_plot <- ggplot(tax_all_pcoa, aes(x = Axis.1, y = Axis.2, fill = UserName)) +
  geom_point(color = "black", alpha=0.75, pch = 21, size = 2, alpha = 0.5) +
  #geom_line(aes(color = UserName)) +
  stat_ellipse(aes(color = UserName), type = "norm", linetype = 2, level = 0.95, alpha = 0.3) +
  scale_fill_manual(name = "Subject", values = pal) + 
  scale_color_manual(values = pal) +
  xlab(paste0("PC 1 [",percent_var[1],"%]")) +
  ylab(paste0("PC 2 [",percent_var[2],"%]")) +
  theme_classic() +                                                                      
    theme(legend.position = "none",
        legend.title.align = 0.5,
        legend.text = element_text(size = 9),
        axis.text = element_text(size = 9)) +
  guides(color = F, fill = guide_legend(ncol = 4)) 
  #theme(legend.title = element_text("Subject"))

tax_all_plot


```

```{r all_func, echo = F, include = F, fig.height = 4, fig.width =4}

func_all <- read.delim("data/processed_KEGG/preprocessed_KEGG_modules_all_clr.txt", row = 1)

# drop soylent 
func_all_ns <- func_all[, !colnames(func_all) %in% soylent]

#make dist matrix
func_all_dist <- dist(t(func_all_ns))

# make pcoa
func_all_pcoa <- data.frame(pcoa(func_all_dist)$vectors)

eigen <- pcoa(func_all_dist)$values$Eigenvalues

percent_var <- signif(eigen/sum(eigen), 4)*100

# move rownames to a column
func_all_pcoa <- rownames_to_column(func_all_pcoa, var = "X.SampleID")

#merge map and PCOA by SampleID - select both lines and run together - won't work otherwise
func_all_pcoa <- inner_join(func_all_pcoa, map_sample, by = 'X.SampleID')

func_all_pcoa$UserName <- gsub(pattern = "MCTs", "", func_all_pcoa$UserName)

func_all_plot <- ggplot(func_all_pcoa, aes(x = Axis.1, y = Axis.2, fill = UserName)) +
  geom_point(color = "black", alpha=0.75, pch = 21, size = 2, alpha = 0.5) +
  #geom_line(aes(color = UserName)) +
  stat_ellipse(aes(color = UserName), type = "norm", linetype = 2, level = 0.95, alpha = 0.3) +
  scale_fill_manual(name = "Subject", values = pal) + 
  scale_color_manual(values = pal) +
  xlab(paste0("PC 1 [",percent_var[1],"%]")) +
  ylab(paste0("PC 2 [",percent_var[2],"%]")) +
  theme_classic() +                                                                      
    theme(legend.position = "none",
        legend.title.align = 0.5,
        legend.text = element_text(size = 9),
        axis.text = element_text(size = 9)) +
  guides(color = F, fill = guide_legend(ncol = 4)) 
  #theme(legend.title = element_text("Subject"))

func_all_plot
```

```{r food_micro_pro, echo = F, include = F, fig.height=4, fig.width=4}
# make pcoas 
pcoa_f <- as.data.frame(pcoa(food_dist)$vectors)
pcoa_t <- as.data.frame(pcoa(tax_dist)$vectors)

# procrustes
pro <- procrustes(pcoa_f, pcoa_t)
pro_test <- protest(pcoa_f, pcoa_t, perm = 999)

eigen <- sqrt(pro$svd$d)
percent_var <- signif(eigen/sum(eigen), 4)*100

beta_pro <- data.frame(pro$X)
trans_pro <- data.frame(pro$Yrot)
beta_pro$UserName <- rownames(beta_pro)
beta_pro$type <- "Food (Unweighted Unifrac)"
trans_pro$UserName <- rownames(trans_pro)
trans_pro$type <- "Microbiome (CLR-Euclidean)"

colnames(trans_pro) <- colnames(beta_pro)

pval <- signif(pro_test$signif, 1)

plot <- rbind(beta_pro, trans_pro)

food_micro <- ggplot(plot) +
  geom_point(size = 4, alpha=0.75, aes(x = Axis.1, y = Axis.2, fill = type), pch=21) +
  scale_fill_manual(values = c("#5dd047", "#E71D36")) +
  theme_bw() +
  geom_line(aes(x= Axis.1, y=Axis.2, group=UserName), col = "black", alpha = 0.7) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(size = 10),
        legend.title = element_blank(),
        legend.key.size = unit(0.2, "in"),
        legend.text = element_text(size=5),
        legend.position = 'bottom',
        axis.text = element_text(size=5),
        axis.title = element_text(size=8)) +
  annotate("text", x = 0.3, y = -0.27, label = paste0("p-value=",pval)) +
  xlab(paste0("PC 1 [",percent_var[1],"%]")) +
  ylab(paste0("PC 2 [",percent_var[2],"%]")) 

food_micro
```

```{r no_tree_food_micro_pro, echo = F, include = F, fig.height=4, fig.width=4}
# make pcoas 
pcoa_nt <- as.data.frame(pcoa(no_tree_dist)$vectors)
pcoa_t <- as.data.frame(pcoa(tax_dist)$vectors)

# procrustes
pro <- procrustes(pcoa_nt, pcoa_t)
pro_test <- protest(pcoa_nt, pcoa_t, perm = 999)

eigen <- sqrt(pro$svd$d)
percent_var <- signif(eigen/sum(eigen), 4)*100

beta_pro <- data.frame(pro$X)
trans_pro <- data.frame(pro$Yrot)
beta_pro$UserName <- rownames(beta_pro)
beta_pro$type <- "Food (Euclidean)"
trans_pro$UserName <- rownames(trans_pro)
trans_pro$type <- "Microbiome (CLR-Euclidean)"

colnames(trans_pro) <- colnames(beta_pro)

pval <- signif(pro_test$signif, 1)

plot <- rbind(beta_pro, trans_pro)

nt_micro <- ggplot(plot) +
  geom_point(size = 4, alpha=0.75, aes(x = Axis.1, y = Axis.2, fill = type), pch=21) +
  scale_fill_manual(values = c("#02111D", "#E71D36")) +
  theme_bw() +
  geom_line(aes(x= Axis.1, y=Axis.2, group=UserName), col = "black", alpha = 0.7) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(size = 10),
        legend.title = element_blank(),
        legend.key.size = unit(0.2, "in"),
        legend.text = element_text(size=5),
        legend.position = 'bottom',
        axis.text = element_text(size=5),
        axis.title = element_text(size=8)) +
  annotate("text", x = -90, y = -78, label = paste0("p-value=",pval)) +
  xlab(paste0("PC 1 [",percent_var[1],"%]")) +
  ylab(paste0("PC 2 [",percent_var[2],"%]")) 

nt_micro
```


```{r nutr_micro_pro, echo = F, include = F, fig.height = 4, fig.width = 4}
# make pcoas 
pcoa_n <- as.data.frame(pcoa(nutr_dist)$vectors)
pcoa_t <- as.data.frame(pcoa(tax_dist)$vectors)

# procrustes
pro <- procrustes(pcoa_n, pcoa_t)
pro_test <- protest(pcoa_n, pcoa_t, perm = 999)

eigen <- sqrt(pro$svd$d)
percent_var <- signif(eigen/sum(eigen), 4)*100

beta_pro <- data.frame(pro$X)
trans_pro <- data.frame(pro$Yrot)
beta_pro$UserName <- rownames(beta_pro)
beta_pro$type <- "Nutrient (Euclidean)"
trans_pro$UserName <- rownames(trans_pro)
trans_pro$type <- "Microbiome (CLR-Euclidean)"

colnames(trans_pro) <- colnames(beta_pro)

pval <- signif(pro_test$signif, 1)

plot <- rbind(beta_pro, trans_pro)

nutr_micro <- ggplot(plot) +
  geom_point(size = 4, alpha=0.75, aes(x = Axis.1, y = Axis.2, fill = type), pch=21) +
  scale_fill_manual(values = c("#E71D36", "#2BBAA7")) +
  theme_bw() +
  geom_line(aes(x= Axis.1, y=Axis.2, group=UserName), col = "black", alpha = 0.7) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(size = 10),
        legend.title = element_blank(),
        legend.key.size = unit(0.2, "in"),
        legend.text = element_text(size=5),
        legend.position = 'bottom',
        axis.text = element_text(size=5),
        axis.title = element_text(size=8)) +
  annotate("text", x = -0.17, y = -0.22, label = paste0("p-value=",pval)) +
  xlab(paste0("PC 1 [",percent_var[1],"%]")) +
  ylab(paste0("PC 2 [",percent_var[2],"%]")) 

nutr_micro




```

```{r func_food_pro, echo = F, include = F, fig.height = 4, fig.width = 4}
# make pcoas 
pcoa_fo <- as.data.frame(pcoa(food_dist)$vectors)
pcoa_fu <- as.data.frame(pcoa(func_dist)$vectors)

# procrustes
pro <- procrustes(pcoa_fo, pcoa_fu)
pro_test <- protest(pcoa_fo, pcoa_fu, perm = 999)

eigen <- sqrt(pro$svd$d)
percent_var <- signif(eigen/sum(eigen), 4)*100

beta_pro <- data.frame(pro$X)
trans_pro <- data.frame(pro$Yrot)
beta_pro$UserName <- rownames(beta_pro)
beta_pro$type <- "Food (Unweighted Unifrac)"
trans_pro$UserName <- rownames(trans_pro)
trans_pro$type <- "Function (CLR-Euclidean)"

colnames(trans_pro) <- colnames(beta_pro)

pval <- signif(pro_test$signif, 1)

plot <- rbind(beta_pro, trans_pro)

func_food <- ggplot(plot) +
  geom_point(size = 4, alpha=0.75, aes(x = Axis.1, y = Axis.2, fill = type), pch=21) +
  scale_fill_manual(values = c("#02111D", "pink")) +
  theme_bw() +
  geom_line(aes(x= Axis.1, y=Axis.2, group=UserName), col = "black", alpha = 0.7) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(size = 10),
        legend.title = element_blank(),
        legend.key.size = unit(0.2, "in"),
        legend.text = element_text(size=5),
        legend.position = 'bottom',
        axis.text = element_text(size=5),
        axis.title = element_text(size=8)) +
  annotate("text", x = 0.3, y = -0.22, label = paste0("p-value=",pval)) +
  xlab(paste0("PC 1 [",percent_var[1],"%]")) +
  ylab(paste0("PC 2 [",percent_var[2],"%]")) 

func_food



```
```{r nutr_func_pro, echo = F, include = F, fig.height = 4, fig.width = 4}
# make pcoas 
pcoa_n <- as.data.frame(pcoa(nutr_dist)$vectors)
pcoa_fu <- as.data.frame(pcoa(func_dist)$vectors)

# procrustes
pro <- procrustes(pcoa_n, pcoa_fu)
pro_test <- protest(pcoa_n, pcoa_fu, perm = 999)

eigen <- sqrt(pro$svd$d)
percent_var <- signif(eigen/sum(eigen), 4)*100

beta_pro <- data.frame(pro$X)
trans_pro <- data.frame(pro$Yrot)
beta_pro$UserName <- rownames(beta_pro)
beta_pro$type <- "Nutrient (Euclidean)"
trans_pro$UserName <- rownames(trans_pro)
trans_pro$type <- "Function (CLR-Euclidean)"

colnames(trans_pro) <- colnames(beta_pro)

pval <- signif(pro_test$signif, 1)

plot <- rbind(beta_pro, trans_pro)

nutr_func <- ggplot(plot) +
  geom_point(size = 4, alpha=0.75, aes(x = Axis.1, y = Axis.2, fill = type), pch=21) +
  scale_fill_manual(values = c("pink", "#2BBAA7")) +
  theme_bw() +
  geom_line(aes(x= Axis.1, y=Axis.2, group=UserName), col = "black", alpha = 0.7) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(size = 10),
        legend.title = element_blank(),
        legend.key.size = unit(0.2, "in"),
        legend.text = element_text(size=5),
        legend.position = 'bottom',
        axis.text = element_text(size=5),
        axis.title = element_text(size=8)) +
  annotate("text", x = -0.17, y = -0.22, label = paste0("p-value=",pval)) +
  xlab(paste0("PC 1 [",percent_var[1],"%]")) +
  ylab(paste0("PC 2 [",percent_var[2],"%]")) 

nutr_func




```
```{r prediction, echo = F, include = F, fig.height = 4, fig.width = 4}

# rename food distance matrix
foodbeta <- as.matrix(food_dist)

# rename taxonomy table
taxa7 <- t(tax)

foodbeta <- foodbeta[rownames(foodbeta) %in% rownames(taxa7),colnames(foodbeta) %in% rownames(taxa7)]
taxa7 <- taxa7[rownames(taxa7) %in% rownames(foodbeta),]

# iterate through k = 1:31 (number of neighbors)
# for each k, predict taxa and get correlation
cors.mb <- sapply(1:31, function(k) {
  taxa7hat <- taxa7
  for(i in 1:nrow(taxa7hat)) taxa7hat[i,] <- colMeans(taxa7[order(foodbeta[i,])[-1][1:k],,drop=F]);
  mean(sapply(1:nrow(taxa7hat), function(ixx) cor(taxa7hat[ixx,], taxa7[ixx,],method='spear')))
})

# as above but with random sets of neighbors
set.seed(7)
mc.cors.mb <- t(sapply(1:31,function(k) {
  replicate(20,{
    taxa7hat.mc <- taxa7;
    for(i in 1:nrow(taxa7hat.mc)) taxa7hat.mc[i,] <- colMeans(taxa7[sample((1:nrow(taxa7hat.mc))[-i])[1:k],,drop=F]);
    mean(sapply(1:nrow(taxa7hat.mc), function(ixx) cor(taxa7hat.mc[ixx,], taxa7[ixx,],method='spear')))
    })
}))


#remake Dan's plot in ggpolt with 10x the lines, but at least i know how to change it :P
plot <- as.data.frame(cbind(cors.mb,mc.cors.mb))
plot <- rownames_to_column(plot, var = "k")
plot$mean_mc.cors.mb <- rowMeans(plot[3:ncol(plot)])
plot1 <- plot[,c("k", "cors.mb", "mean_mc.cors.mb")]
plot1 <- melt(plot1, id = "k")
plot2 <- plot[,!colnames(plot) %in% c("cors.mb", "mean_mc.cors.mb")]
plot2 <- melt(plot2, id = "k")

# calculate difference between model and random
diff <- signif(sum(plot1$value - plot2$value), 2)

pre <- ggplot() +
  geom_line(data = plot2, aes(x = as.numeric(k), y = value, group = variable), color = "darkgrey", size = .2, alpha = 0.5) +
  geom_line(size =.8) +
  geom_line(data = plot1, aes(x=as.numeric(k), y = value, group=variable, color = variable), alpha = 0.7, size = 1) + 
  scale_color_manual(values = c("red", "darkgrey"), labels = c("Model", "Random")) +
  labs(x = "Number of neighbors", y="Correlation") +
  theme_classic() +
  theme(legend.position = "bottom", 
        legend.title = element_blank(),
        legend.direction = "horizontal") +
  annotate("text", x = 25, y = 0.4, label = paste0("Mean difference=",diff), size = 3.5)

pre

```



```{r figure_2, echo=F, fig.height = 8.8, fig.width= 10}

top <- plot_grid(tax_all_plot, food_all_plot, labels = c("A", "B"), rel_widths = c(1,1.5))
bottom <- plot_grid(food_micro, nutr_micro, labels = c("C", "D"), nrow = 1)

plot_grid(top,bottom, nrow = 2, rel_heights = c(1, 1.2))


```



```{r summary_tax, echo = F, include = F, fig.height = 4, fig.width =4}

tax_sum <- read.delim("data/processed_UN_tax/UN_taxonomy_clr_s.txt", row=1)

# drop soylent 
tax_sum_ns <- tax_sum[, !colnames(tax_sum) %in% c("MCTs11", "MCTs12")]

#make dist matrix
tax_sum_dist <- dist(t(tax_sum_ns))

# make pcoa
tax_sum_pcoa <- data.frame(pcoa(tax_sum_dist)$vectors)

eigen <- pcoa(tax_sum_dist)$values$Eigenvalues

percent_var <- signif(eigen/sum(eigen), 4)*100

# move rownames to a column
tax_sum_pcoa <- rownames_to_column(tax_sum_pcoa, var = "UserName")

#merge map and PCOA by SampleID - select both lines and run together - won't work otherwise
tax_sum_pcoa <- inner_join(tax_sum_pcoa, map_username, by = 'UserName')

tax_sum_pcoa$UserName <- gsub(pattern = "MCTs", "", tax_sum_pcoa$UserName)

tax_sum_plot <- ggplot(tax_sum_pcoa, aes(x = Axis.1, y = Axis.2, fill = UserName)) +
  geom_point(color = "black", alpha=0.75, pch = 21, size = 2, alpha = 0.5) +
  #geom_line(aes(color = UserName)) +
  #stat_ellipse(aes(color = UserName), type = "norm", linetype = 2, level = 0.95, alpha = 0.3) +
  scale_fill_manual(name = "Subject", values = pal) + 
  scale_color_manual(values = pal) +
  xlab(paste0("PC 1 [",percent_var[1],"%]")) +
  ylab(paste0("PC 2 [",percent_var[2],"%]")) +
  theme_classic() +                                                                      
    theme(legend.position = "none",
        legend.title.align = 0.5,
        legend.text = element_text(size = 9),
        axis.text = element_text(size = 9)) +
  guides(color = F, fill = guide_legend(ncol = 4)) 
  #theme(legend.title = element_text("Subject"))

tax_sum_plot


```

```{r sum_food, echo = F, include = F, fig.height = 4, fig.width =6}

food_sum <- read.delim("data/processed_food/dhydrt_smry_no_soy_beta/unweighted_unifrac_dhydrt.smry.no.soy.txt", row = 1)


food_sum_pcoa <- data.frame(pcoa(food_sum)$vectors)

eigen <- pcoa(food_sum)$values$Eigenvalues

percent_var <- signif(eigen/sum(eigen), 4)*100

# move rownames to a column
food_sum_pcoa <- rownames_to_column(food_sum_pcoa, var = "UserName")

#merge map and PCOA by SampleID - select both lines and run together - won't work otherwise
food_sum_pcoa <- inner_join(food_sum_pcoa, map_username, by = 'UserName')

food_sum_pcoa$UserName <- gsub(pattern = "MCTs", "", food_sum_pcoa$UserName)

food_sum_plot <- ggplot(food_sum_pcoa, aes(x = Axis.1, y = Axis.2, fill = UserName)) +
  geom_point(color = "black", alpha=0.75, pch = 21, size = 2, alpha = 0.5) +
  #geom_line(aes(color = UserName)) +
  #stat_ellipse(aes(color = UserName), type = "norm", linetype = 2, level = 0.95, alpha = 0.3) +
  scale_fill_manual(name = "Subject", values = pal) + 
  scale_color_manual(values = pal) +
  xlab(paste0("PCOA 1 [",percent_var[1],"%]")) +
  ylab(paste0("PCOA 2 [",percent_var[2],"%]")) +
  theme_classic() +                                                                      
  theme(legend.position = "right",
        legend.title.align = 0.5,
        legend.text = element_text(size = 9),
        axis.text = element_text(size = 9)) +
  guides(color = F, fill = guide_legend(ncol = 4)) 
  #theme(legend.title = element_text("Subject"))

food_sum_plot

```


