---
title: "PCOA by genus"
author: "Abby"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE, message = FALSE}

require(rmarkdown)
require(knitr)
require(RColorBrewer) 
require(cowplot)
require(tidyverse)
require(stringr)
require(dplyr)
require(ape)
require(vegan)

opts_knit$set(root.dir = "/Users/abby/Documents/Projects/dietstudy/")
opts_chunk$set(echo = TRUE, fig.path = "Figs/", dev = c("png", "pdf"), dpi = 300)

```

```{r load long map, echo = FALSE}
map <- read.table("data/maps/SampleID_map.txt", sep = "\t", header = T, comment = "")
map_username <- read.table("data/maps/UserName_map.txt", sep = "\t", header = T, comment = "")

# set up colors
cols <- brewer.pal(11, "Spectral")
cols2 <- colorRampPalette(cols)
my_cols <- rev(cols2(15))

```


```{r import beta div, include =F, message = F}

#normalized taxonomy beta diversity (chi-sq distance matrix)
#tax_beta <- read.delim("data/processed_tax/taxa_beta/bray_curtis_taxonomy_norm_s.txt", sep = "\t", row.names = 1)

tax_beta <- read.delim("data/processed_tax/strain_beta/weighted_unifrac_strain.txt", sep = "\t", row.names = 1)

# clr taxonomy
#tax <- read.delim("data/processed_tax/taxonomy_clr.txt", sep ="\t", row.names = 1)
#tax_beta <- as.matrix(vegdist(t(tax), method = "euclidian"))

# counts for coloring
tax_n <- read.delim("data/processed_tax/taxonomy_norm_g.txt", sep = "\t", row.names = 1)

# sort tax_n by relative abundance
tax_n <- tax_n[order(rowMeans(tax_n), decreasing = T),]

# Get the top for for plotting
gtaxa <- tax_n[1:4,]
gtaxa <- t(gtaxa)

# apply cut to the genus relative abundances for plotting
myrownames <- rownames(gtaxa)
gtaxa <- apply(gtaxa, 2, function(x) cut(x, breaks = seq(0, max(x), length.out = 15)))
rownames(gtaxa) <- myrownames

# add genus ra to the map
gtaxa_map <- as.data.frame(gtaxa)
colnames(gtaxa_map) <- gsub(".*g__", "", colnames(gtaxa_map))
gtaxa_map <- rownames_to_column(gtaxa_map, "X.SampleID")
gtaxa_map <- inner_join(map, gtaxa_map, by = "X.SampleID")


```

Make the pcoa plot

```{r pcoa, echo = F, fig.width=15, fig.height = 15}

#betad as matrix 
plot <- data.frame(pcoa(tax_beta)$vectors)

# move rownames to a column
plot <- rownames_to_column(plot, var = "X.SampleID")

#merge map and PCOA by SampleID - select both lines and run together - won't work otherwise
plot <- inner_join(plot, gtaxa_map, by = 'X.SampleID')

Bactr <- ggplot(plot, aes(x = Axis.1, y = Axis.2)) +
  geom_point(aes(fill = Bacteroides), alpha=1, pch = 21, size = 5) +
  scale_fill_manual(values = my_cols) +
  scale_color_manual(values = c("black", "dark grey")) +
  #scale_shape_manual(values = shape_pal3) +
  stat_ellipse(aes(group = UserName), color = "dark grey", type = "norm", linetype = 2, level = 0.95) +
  labs(title="Relative Abundance of Bacteroides ") +
  guides(fill = guide_legend(override.aes = list(alpha=1)), size = FALSE, col = FALSE) +
  #guides(size = FALSE, fill = FALSE) +
  theme_classic(base_family = "Helvetica") +                                                                      
  theme(plot.title = element_text(size = 14, hjust = 0.5),
        legend.position = "bottom",
        legend.title = element_blank())


Alis <- ggplot(plot, aes(x = Axis.1, y = Axis.2)) +
  geom_point(aes(fill = Alistipes), alpha=1, pch = 21, size = 5) +
  scale_fill_manual(values = my_cols) +
  scale_color_manual(values = c("black", "dark grey")) +
  #scale_shape_manual(values = shape_pal3) +
  stat_ellipse(aes(group = UserName), color = "dark grey", type = "norm", linetype = 2, level = 0.95) +
  labs(title="Relative Abundance of Alistipes") +
  guides(fill = guide_legend(override.aes = list(alpha=1)), size = FALSE, col = FALSE) +
  #guides(size = FALSE, fill = FALSE) +
  theme_classic(base_family = "Helvetica") +                                                                      
  theme(plot.title = element_text(size = 14, hjust = 0.5),
        legend.position = "bottom",
        legend.title = element_blank())


Prev <- ggplot(plot, aes(x = Axis.1, y = Axis.2)) +
  geom_point(aes(fill = plot$Prevotella), alpha=1, pch = 21, size = 5) +
  scale_fill_manual(values = my_cols) +
  scale_color_manual(values = c("black", "dark grey")) +
  #scale_shape_manual(values = shape_pal3) +
  stat_ellipse(aes(group = UserName), color = "dark grey", type = "norm", linetype = 2, level = 0.95) +
  labs(title="Relative Abundance of Prevotella") +
  guides(fill = guide_legend(override.aes = list(alpha=1)), size = FALSE, col = FALSE) +
  #guides(size = FALSE, fill = FALSE) +
  theme_classic(base_family = "Helvetica") +                                                                      
  theme(plot.title = element_text(size = 14, hjust = 0.5),
        legend.position = "bottom",
        legend.title = element_blank())

Faecali <- ggplot(plot, aes(x = Axis.1, y = Axis.2)) +
  geom_point(aes(fill = plot$Faecalibacterium), alpha=1, pch = 21, size = 5) +
  scale_fill_manual(values = my_cols) +
  scale_color_manual(values = c("black", "dark grey")) +
  #scale_shape_manual(values = shape_pal3) +
  stat_ellipse(aes(group = UserName), color = "dark grey", type = "norm", linetype = 2, level = 0.95) +
  labs(title="Relative Abundance of Faecalibacterium") +
  guides(fill = guide_legend(override.aes = list(alpha=1)), size = FALSE, col = FALSE) +
  #guides(size = FALSE, fill = FALSE) +
  theme_classic(base_family = "Helvetica") +                                                              
  theme(plot.title = element_text(size = 14, hjust = 0.5),
        legend.position = "bottom",
        legend.title = element_blank())



plot_grid(Bactr, Alis, Prev, Faecali) 
          




```






