---
title: "Beta diversity variability - fiber"
author: "Abby"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE, message = FALSE}

require(rmarkdown)
require(knitr)
require(RColorBrewer) 
require(cowplot)
require(tidyverse)
require(stringr)
require(dplyr)
require(ape)
require(vegan)

opts_knit$set(root.dir = "/Users/abby/Documents/Projects/dietstudy/")
opts_chunk$set(echo = TRUE, fig.path = "Figs/", dev = c("png", "pdf"), dpi = 300)

```

```{r load long map, echo = FALSE}
map <- read.table("data/maps/SampleID_map.txt", sep = "\t", header = T, comment = "")
map_username <- read.table("data/maps/UserName_map.txt", sep = "\t", header = T, comment = "")

# set up colors
cols <- brewer.pal(12, "Set3")
cols2 <- colorRampPalette(cols)
```


```{r import beta div, include =F, message = F}
# import beta diversity
food_beta <- read.delim("data/processed_food/fiber_beta/unweighted_unifrac_fiber.txt", sep = "\t", row.names = 1)

#normalized taxonomy
#tax_beta <- read.delim("data/processed_tax/taxa_beta/bray_curtis_taxonomy_norm_s.txt", sep = "\t", row.names = 1)

#tax <- read.delim("data/processed_tax/taxonomy_norm_s.txt", sep = "\t", row.names = 1)

# clr taxonomy
tax <- read.delim("data/processed_tax/taxonomy_clr_s.txt", sep ="\t", row.names = 1)

#tax_beta <- as.matrix(vegdist(t(tax), method = "bray", binary=FALSE, diag=FALSE, upper=FALSE, na.rm = FALSE))
tax_beta <- as.matrix(vegdist(t(tax), method = "euclidian"))

 
# tax_beta_chi <- read.delim("data/processed_tax/taxa_beta/chisq_taxonomy_norm_s.txt", sep = "\t", row.names =1)



# import matching maps
food_map <- read.table("data/maps/food_map.txt", header = T, sep = "\t", comment = "")
tax_map <- read.table("data/maps/taxonomy_norm_map.txt", header = T, sep = "\t", comment = "")

# calculate mean of the mean distance to self for each sample, for each UserName (food)
mydist <- NULL

for (i in unique(food_map$UserName)) {
  name <- food_map[food_map$UserName == i,1]
  name <- as.vector(name)
  tmp <- food_beta[rownames(food_beta) %in% name, colnames(food_beta) %in% name]
  num <- rowMeans(tmp, na.rm = T)
  num <- cbind(i,num)
  mydist <- rbind(num, mydist)
  colnames(mydist) <- c("UserName", "food_mean_beta_div")
}

food_dist <- as.data.frame(mydist)
food_dist$food_mean_beta_div <- as.character(food_dist$food_mean_beta_div)
food_dist$food_mean_beta_div <- as.numeric(food_dist$food_mean_beta_div)


mydist <- NULL

for (i in unique(tax_map$UserName)) {
  name <- tax_map[tax_map$UserName == i,1]
  name <- as.vector(name)
  tmp <- tax_beta[rownames(tax_beta) %in% name, colnames(tax_beta) %in% name]
  num <- rowMeans(tmp, na.rm = T)
  num <- cbind(i,num)
  mydist <- rbind(num, mydist)
  colnames(mydist) <- c("UserName", "mean_beta_div")
}

tax_dist <- as.data.frame(mydist)
tax_dist <- droplevels(tax_dist)
tax_dist$mean_beta_div <- as.character(tax_dist$mean_beta_div)
tax_dist$mean_beta_div <- as.numeric(tax_dist$mean_beta_div)


```


```{r food div per subject, echo = F}
# Get average microbiome distance to self 
# This will also be used to order the plot
micro_order <- tax_dist %>% 
  group_by(UserName) %>% 
  dplyr::summarise(ave_cloud = median(mean_beta_div, na.rm=T))
# sort by mean
micro_order <- micro_order[order(micro_order$ave_cloud),]
# get factor names for ordering
ord_factor <- as.character(micro_order$UserName)

# calculate median food distance to self
food_order <- food_dist %>% 
  group_by(UserName) %>% 
  dplyr::summarize(food_cloud = median(food_mean_beta_div))

# create the chisq version
# micro_order_chi <- tax_dist_chi %>% 
#   group_by(UserName) %>% 
#   dplyr::summarise(ave_cloud = median(mean_beta_div, na.rm=T))

# write beta div cloud sizes to file for comparisons elsewhere
write.table(micro_order, "analysis/beta_diversity/beta_div_cloud.txt", sep = "\t", col.names = T, row.names = F)
write.table(food_order, "analysis/fiber/fiber_beta_div_cloud.txt", sep = "\t", col.names = T, row.names = F)


```





```{r food plot, echo = F}

# set colors
set.seed(7)
subject_cols <- (sample(cols2(34)))

plot_food_per_subject <- food_dist # %>%
  #filter(UserName != "MCTs06", #Infrequent bowel movements
       #  UserName != "MCTs29"  #Infrequent bowel movements
       #  ) 
plot_food_per_subject <- merge(plot_food_per_subject, map_username)

# reorder by ordered factor
plot_food_per_subject$UserName <- factor(plot_food_per_subject$UserName, levels = ord_factor)

# make plot (switch directionality)
diet <- ggplot(data = plot_food_per_subject, aes(x = UserName, y = food_mean_beta_div, fill = UserName)) +
  geom_boxplot(fill = subject_cols, outlier.shape = NA, lwd = .25) +
  geom_jitter(shape = 21, fill = NA, size = 0.5, width = 0.2, alpha = 0.5) +
  theme_classic() +
  theme(axis.title.x = element_text(size = 9), 
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "none") +
  labs(y = "Fiber beta diversity variability (Unweighted Unifrac)", x = " ") +
  coord_flip()


```

```{r microbiome div per subject, echo = F}

plot_tax_per_subject <- tax_dist #%>%
  #filter(UserName != "MCTs06", #Infrequent Bowel Movements
        # UserName != "MCTs29"  #Infrequent Bowel Movements
        # ) 
plot_tax_per_subject <- merge(plot_tax_per_subject, map_username)

plot_tax_per_subject$UserName <- gsub("MCTs", "", plot_tax_per_subject$UserName)
ord_factor <- gsub("MCTs", "", ord_factor)

# apply ordering
plot_tax_per_subject$UserName <- factor(plot_tax_per_subject$UserName, levels = ord_factor)

# plot taxonomy diversity
micro_tax <- ggplot(data = plot_tax_per_subject, aes(x = UserName, y = mean_beta_div, fill = UserName)) +
  geom_boxplot(fill = subject_cols, outlier.shape = NA, lwd = .25) +
  geom_jitter(shape = 21, fill = NA, size = 0.5, width = 0.2, alpha = 0.5) +
  theme_classic() +
  theme(axis.title.x = element_text(size = 9),
        axis.title.y = element_text(size = 9),
        axis.text.y = element_text(size = 6),
        legend.position = "none") +
  labs(y = "Microbiome beta diversity variabitliy (CLR-Euc.)", x = "") +
  coord_flip()
  
```

```{r plotdietmicrobiome, echo = F, message = F, fig.width=10, fig.height=4}
plot_grid(micro_tax, diet, #labels = c("D", "E") , 
          ncol = 2, align = "h", rel_widths = c(1.0,1.0))

```


```{r micro v food cloud size, echo = F, fig.height=4, fig.width=4}
plot <- merge(micro_order, food_order)

ggplot(plot, aes(y = food_cloud, x = ave_cloud)) +
  geom_smooth(method = "lm", color = "black", fill = "grey") + 
  geom_point(aes(fill = UserName), size = 3, color = subject_cols) +
  geom_point(aes(fill = UserName), shape = 1, size =3, color = "black") +
  theme(legend.position = "none",
        axis.title = element_text(size = 10)) +
  labs(y = "Fiber mean distance to self", x = "Microbiome mean distance to self")

cor.test(plot$food_cloud, plot$ave_cloud, method = "spearman")


# without soylent?
soylent <- c("MCTs11", "MCTs12")
soy_plot <- plot[!plot$UserName %in% soylent,]

cor.test(soy_plot$food_cloud, soy_plot$ave_cloud, method = "spearman")

```



Fold difference for the variation in non-outlier microbiome cloud size:
```{r fold difference, echo = F}
# calculate the fold difference for the mean variation
# first drop subjects
micro_order <- micro_order 

# fold change(ratio)
(max(micro_order$ave_cloud)/min(micro_order$ave_cloud)) 

food_order <- food_order #%>% filter(UserName != "MCTs11", UserName != "MCTs12")

# calculate fold change foo
max(food_order$food_cloud)/min(food_order$food_cloud)

```



```{r foods beta cloud, echo=F}
# Are any foods associated with beta-diversity cloud size?
food <- read.table("data/processed_food/fiber.txt", header = T, sep = "\t", comment = "")

# get the foods in the correct format
food <- remove_rownames(food)
food <- column_to_rownames(food, var = "taxonomy")
food <- food %>% select(-X.FoodID)

# drop foods from groups that don't have high fiber contnent

tomatch <- c("L1_Eggs", "L1_Fats_Oils_and_Salad_Dressings", "L1_Milk_and_Milk_Products", "L1_Meat_Poultry_Fish_and_Mixtures", "L1_Sugars_Sweets_and_Beverages")
food <- food[grep(paste(tomatch, collapse= "|"), rownames(food), invert = T),]


#normalizing the fiber like I did in the procrustes analysis doesn't change anything substantially 


# collapse by taxa level 3
split <- strsplit(rownames(food),";")             # Split and rejoin on lv7 to get species level
foodStrings <- sapply(split,function(x) paste(x[1:1],collapse=";"))
food <- rowsum(food,foodStrings)              # Collapse by taxonomy name

# Sort by average abundance
food <- food[order(rowMeans(food),decreasing=T),]

# summarize by person
#initiate the dataframe with the correct information
food_subject <- data.frame(matrix(nrow=nrow(food), ncol=0))
rownames(food_subject) <- rownames(food)

# fix naming of food_map
colnames(food_map)[1] <- "X.SampleID"

#loop through and summarize by username
for (i in unique(food_map$UserName)){
  subgroup <- food_map[food_map$UserName == i,]
  if(dim(subgroup)[1] <= 4){ 
    NULL
  }else{
  sub <- food[(colnames(food) %in% subgroup[,"X.SampleID"])]
  tmp <- as.data.frame(rowMeans(sub))
  colnames(tmp) <- i
  food_subject <- cbind(food_subject,tmp)
  } 
}

# Normalize
food_subject <- sweep(food_subject, 2, colSums(food_subject), "/")

# Sort by average abundance
food_subject <- food_subject[order(rowMeans(food_subject),decreasing=T),]


# subset to same number of subjects
food_subject <- food_subject[,colnames(food_subject) %in% micro_order$UserName]
micro_order <- micro_order[micro_order$UserName %in% colnames(food_subject),]
micro_order <- micro_order[order(micro_order$UserName),]

# get correlations pvalues
pvals <- apply(food_subject, 1, function(x) {cor.test(x, micro_order$ave_cloud, method = "spearman", exact = F)$p.value})
cors <- apply(food_subject, 1, function(x) {cor(x, micro_order$ave_cloud, method = "spearman", use="pairwise.complete.obs")})

qvals <- p.adjust(pvals, method = "fdr")

qvals <- as.data.frame(qvals)
cors <- as.data.frame(cors)

# nothing correlated significantly with median beta diversity if we leave out the outliers
# if we include the outliers, then
out <- merge(qvals, cors, by = 0)

out <- out[order(out$qvals, decreasing = F),]
out <- remove_rownames(out)

colnames(out)[1] <- "FiberSource"

out <- out[out$qvals <= 0.25,]
out <- na.omit(out)

out
```

```{r food sig plots, echo = F, fig.height=4, fig.width=4}
plot <- as.data.frame(t(food_subject))
mynames <- rownames(plot)
plot <- as.data.frame(plot[,colnames(plot) %in% out$FiberSource])
colnames(plot) <- "Fruit_Fiber"
plot$UserName <- mynames 
plot <- merge(micro_order, plot)

mytest <- cor.test(1/plot$ave_cloud, plot$Fruit_Fiber, method = "spearman", exact =F)

rho <- paste("italic(r) == ", round(mytest$estimate, 2))
p <- paste("italic(pval) ==", round(out$qvals, 2)) # sub in the fdr adjusted pvalue, unadjusted = 0.03
labels = data.frame(x = 0.3, y =0.07, label = paste(rho, p, sep = " ~ "))

ggplot(data = plot, aes(x = Fruit_Fiber, y = 1/ave_cloud)) +
  geom_smooth(method = "lm", color = "black", fill = "grey") +
  geom_point(aes(fill = UserName), color = subject_cols[1:34], size = 3) +
  geom_point(aes(fill = UserName), shape = 1, size =3, color = "black") +
  theme(legend.position = "none") +
  geom_text(data = labels, aes(x=x, y=y,
             label = label),
             parse = T, size = 3) +
  labs(y = "Microbiome Stability")


# trend towards significance - R = 0.35 and qval = 0.18 

# when looking at level 2, there are two possible groups with qvals <0.25, and a large number with qvals around 0.31. Might be something there...
```


```{r food pcoa, echo = F, fig.width=7.5, fig.height = 4}

#betad as matrix 
betadiv <- data.frame(pcoa(food_beta)$vectors)

# move rownames to a column
betadiv <- rownames_to_column(betadiv, var = "X.SampleID")

#merge map and PCOA by SampleID - select both lines and run together - won't work otherwise
betadiv <- inner_join(betadiv, map, by = 'X.SampleID')


Axis.1.2 <- ggplot(betadiv, aes(x = Axis.1, y = Axis.2, fill = UserName)) +
  geom_point(color = "black", alpha=0.75, pch = 21, size = 2) +
  stat_ellipse(aes(color = UserName), type = "norm", linetype = 2, level = 0.95, alpha = 0.3) +
  scale_fill_manual(values = subject_cols) + 
  scale_color_manual(values = subject_cols) +
  labs(title="Dietary Beta-diversity \n(Unweighted Unifrac)") +
  theme_classic() +                                                                      
  theme(plot.title = element_text(size = 14, hjust = 0.5),
        legend.position = "none")


Axis.2.3 <- ggplot(betadiv, aes(x = Axis.3, y = Axis.2, fill = UserName)) +
  geom_point(color = "black", alpha=0.75, pch = 21, size = 2) +
  stat_ellipse(aes(color = UserName), type = "norm", linetype = 2, level = 0.95, alpha = 0.3) +
  scale_fill_manual(values = subject_cols) + 
  scale_color_manual(values = subject_cols) +
  labs(title="Dietary Beta-diversity \n(Unweighted Unifrac)") +
  theme_classic() +                                                                      
  theme(plot.title = element_text(size = 14, hjust = 0.5),
        legend.position = "none")

plot_grid(Axis.1.2, Axis.2.3)

```

```{r food by day, echo = F, fig.width=10.5, fig.height=24}
Axis1.day <- ggplot(betadiv, aes(x = StudyDayNo, y = Axis.1, fill = UserName, droplevels = TRUE)) +
  geom_line(color = "grey") +
  geom_point(color = "black", alpha=0.75, pch = 21, size = 3) +
  scale_fill_manual(values = subject_cols) +
  facet_wrap(~UserName)+
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_text(size = 3),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        strip.text = element_text(size = 7),
        strip.background = element_rect(color = "grey", fill = "white"))
  

Axis2.day <- ggplot(betadiv, aes(x = StudyDayNo, y = Axis.2, fill = UserName, droplevels = TRUE)) +
  geom_line(color = "grey") +
  geom_point(color = "black", alpha=0.75, pch = 21, size = 3) +
  scale_fill_manual(values = subject_cols) +
  facet_wrap(~UserName)+
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_text(size = 3),
        axis.ticks.x = element_blank(),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        strip.text = element_text(size = 7),
        strip.background = element_rect(color = "grey", fill = "white"))


Axis3.day <- ggplot(betadiv, aes(x = StudyDayNo, y = Axis.3, fill = UserName, droplevels = TRUE)) +
  geom_line(color = "grey") +
  geom_point(color = "black", alpha=0.75, pch = 21, size = 3) +
  scale_fill_manual(values = subject_cols) +
  facet_wrap(~UserName)+
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_text(size = 3),
        axis.ticks.x = element_blank(),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        strip.text = element_text(size = 7),
        strip.background = element_rect(color = "grey", fill = "white"))
  

plot_grid(Axis1.day,Axis2.day, Axis3.day, ncol = 1)
```
```{r fiber, echo = F, fig.width = 4, fig.height = 4}
# beta diverstiy variability v. fiber
nutr <- read.table("data/processed_nutr/nutr_totals.txt", sep = "\t", comment = "", header = T)

fiber_smry <- nutr %>% group_by(UserName) %>% dplyr::summarise(fiber = mean(FIBE))

mean(fiber_smry$fiber)
range(fiber_smry$fiber)

nutr_smry <- nutr %>% group_by(UserName) %>% dplyr::summarise(KCAL = mean(KCAL), FIBE = mean(FIBE))
nutr_smry$fk <- (nutr_smry$FIBE/nutr_smry$KCAL)*1000 

mean(nutr_smry$fk)
range(nutr_smry$fk)
sum(nutr_smry$fk > 14)

fiber_smry <- merge(fiber_smry, micro_order)



# drop soylent
fiber_smry <- fiber_smry[!fiber_smry$UserName %in% c("MCTs11", "MCTs12"),]

# Excluding extremely variabile microbiome individuals
#fiber_smry <- fiber_smry[!fiber_smry$UserName %in% c("MCTs06", "MCTs29"),]
# Exlcuding fiber outliers (meeting recs)
#fiber_smry <- fiber_smry[!fiber_smry$UserName %in% c("MCTs07","MCTs16", "MCTs28", "MCTs31"),]

mytest <- cor.test((1/fiber_smry$ave_cloud), fiber_smry$fiber, method = "spearman")

rho <- paste("italic(r) == ", round(mytest$estimate, 3))
p <- paste("italic(pval) ==", round(mytest$p.value, 3))
labels = data.frame(x = 35, y =0.07, label = paste(rho, p, sep = " ~ "))


ggplot(fiber_smry, aes(y = (1/ave_cloud), x = fiber)) +
  geom_smooth(method="lm", color = "black", fill = "grey") + 
  geom_point(aes(fill = UserName), size = 3, shape = 21, alpha = 1) +
  scale_fill_manual(values = c(subject_cols[1:34])) +
  theme_classic() +
  theme(legend.position = "none",
        axis.title = element_text(size = 10)) +
  geom_text(data = labels, aes(x=x, y=y,
             label = label),
             parse = T, size = 3) +
  labs(x = "Average fiber (g/day)", y = "Microbiome Stability\n(inverse variability)")


# after fixing the mislabeling issue and also adjusting taxa with CLR-transformation there is no relationship between fiber and stability.

```





