---
title: "Supplemental Figure 6"
author: "Abby"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    dev: png
---




```{r setup, include=FALSE, message = FALSE}
# this chunck sets up the rmd document

require(rmarkdown)
require(knitr)
require(tidyverse)
require(RColorBrewer) 
require(cowplot)
require(reshape2)
require(ggdendro)
require(vegan)
require(gridExtra)

# set the path for root directory
opts_knit$set(root.dir = "/Users/abby/Documents/Projects/dietstudy/")

# create a directory for the figure and set it's resolution/format
# opts_chunk$set(echo = TRUE, fig.path = "Figs_18_5_11/", dev = c("tiff"), dpi = 300, dev.args = list(compression="lzw"))
opts_chunk$set(echo = TRUE, fig.path = "Figs/", dev = c("pdf","png"), dpi = 300)
```

```{r load long map, echo = FALSE}
#### load the maps for downstream use ####
# full sample map - every possible sample
map <- read.table("data/maps/SampleID_map.txt", sep = "\t", header = T, comment = "")
# map for each subject
map_username <- read.table("data/maps/UserName_map.txt", sep = "\t", header = T, comment = "")
# map of just the smaples with taxonomy information after cleaning
tax_map <- read.table("data/maps/taxonomy_norm_map.txt", sep = "\t", header = T, comment = "")

# set up colors (http://phrogz.net/css/distinct-colors.html)
pal <- rev(c("#ff40f2", "#ff0000", "#008c4b", "#00138c", "#8c235b", "#ffbfbf", "#8c7723", "#468c75", "#8091ff", "#ff80c4", "#8c3123", "#fff2bf", "#40fff2", "#69698c", "#ff0044", "#ff9180", "#e5ff80", "#bffbff", "#5940ff", "#8c696e", "#8c7369", "#858c69", "#40d9ff", "#c480ff", "#ff8c40", "#4b8c00", "#23698c", "#69238c", "#8c4b00", "#bfffbf", "#004b8c", "#eabfff", "#ffc480", "#40ff59", "#80c4ff", "#ffd940" ))
pal1 <- rev(c("#ff0015", "#0073ff", "#adffcb", "#8c0000", "#ffadb4", "#add2ff", "#5f8c70", "#8c5f5f", "#bb00ff", "#5f748c", "#d0ff00", "#67008c", "#00ff5e", "#738c00", "#e9adff", "#008c33", "#f0ffad"))
pal2 <- rev(c("#8c5f63", "#ff0015", "#e9adff", "#003f8c", "#0073ff", "#adffcb", "#738c00", "#d0ff00", "#8c000c", "#67008c", "#bb00ff", "#add2ff", "#008c33", "#00ff5e", "#f0ffad", "#ffadad"))
pal3 <- rev(c("#ff4066", "#8091ff", "#c3ffbf", "#7a5c62", "#bfc8ff", "#7a771f", "#df40ff", "#40ffec", "#fffb80", "#703d7a", "#3d7a74", "#ff0000", "#f4bfff", "#bffff9", "#7a1f1f", "#00107a", "#11ff00", "#ffbfbf", "#4059ff", "#417a3d"))

pal4 <- c("#bf0000", "#f29d3d", "#a3d9b1", "#bfd9ff", "#f780ff", "#ff0000", "#ffe1bf", "#00d957", "#0020f2", "#e60099", "#730f00", "#7f6600", "#336655", "#293aa6", "#a6538a", "#8c4f46", "#e5c339", "#00ffcc", "#333a66", "#40202d", "#f29979", "#fbffbf", "#00b3a7", "#8091ff", "#cc335c", "#594943", "#a3d936", "#003033", "#300059", "#400009", "#cc5200", "#354020", "#39c3e6", "#cbace6", "#d9a3aa", "#7f5940", "#6a8040", "#006fa6", "#cc00ff", "#402910", "#0a4d00", "#566573", "#83008c")

```

# Supplemental Figure:

Clustering of individuals, colored by supplement assignment.

```{r dend_plot, echo = F, fig.width = 10, fig.height=4, message=F}
# import average microbime per person for clustering
microbes <- read.delim("data/processed_UN_tax/UN_taxonomy_norm_s.txt", row = 1)

# create normalized sqrt relative abundance
# this is what we display in the figure, so we cluster using these values
microbes.sq <- sweep(sqrt(microbes), 2, colSums(sqrt(microbes)), "/")


# create distance matrix for clustering
# should update this to what ever method I end up using in the paper (euclidean for clr, but should use a tree method with relative abundance data)
mydist <- vegdist(t(microbes.sq), method = "bray") 
myclust <- hclust(mydist, method = "average")
order <- myclust$order
microbes <- microbes[,order]
ord_factor <- as.character(colnames(microbes))

# save the sim.order - might not need to do this
#save(sim.order, file = "data/order_by_similaritiy.RData")

## Quick visual look at the visual clustering
# plot(myclust);groups <- cutree(myclust, k=3);rect.hclust(myclust, k=3, border = "red")


# create dendrogram of clustering
dend <- as.dendrogram(myclust)

# munging for plotting
ddata <- dendro_data(dend, type = "rectangle")
labs <- label(ddata)
# change class to prevent warning when joining
labs$label<- as.character(labs$label)
map_username$UserName <- as.character(map_username$UserName)
# add map information for plotting
labs <- inner_join(labs, map_username, by = c("label"="UserName" ))
labs$label <- gsub("MCTs", "", labs$label)

# plot dendrogram
dend_plot <- ggplot(segment(ddata)) + 
  geom_segment(aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_label(data=labs, aes(label=label, x =x, y=0, hjust = 0.5, vjust =1, fill = labs$Supplement), size = 3) +
  scale_fill_manual(values = c("#e66101","#5e3c99")) +
  ylim(-0.25, 0.5) +
  theme_dendro() +
  theme(legend.position = c(0.5,0.2),
        legend.direction = "horizontal",
        legend.title = element_blank())

dend_plot


```




```{r plot_major_functions, include =F, fig.width = 7.5, fig.height=6, message = F}

# import microbiome data for function
modules <- read.table("data/processed_KEGG/clean_both_KEGG_modules_table.txt", header = T, row.names = 1, sep = "\t", comment = "")

# double check it's normalized (should be already)
modules = sweep(modules,2,colSums(modules), '/')


# for plotting, limit to top ~30 functions
modules = modules[rowMeans(modules) >= 0.005,]

# sort by highest average relative abundance
modules <- modules[order(rowMeans(modules), decreasing = F),]

# make tax ordering factor
mod_ord_factor <- as.character(rownames(modules))

plot <- as.data.frame(t(modules))
plot <- rownames_to_column(plot, var = "X.SampleID")
plot <- melt(plot, id = "X.SampleID", variable.name = "Modules")

# Check there are no duplicates/sum all of the same species for the same person
plot <- plot %>% group_by(X.SampleID, Modules) %>% dplyr::summarise(newvalue = sum(value))

# create other category for plotting
other <- plot %>% group_by(X.SampleID) %>% dplyr::summarise(newvalue = 1- sum(newvalue))
other$Modules <- "Other"
other <- other %>% select(X.SampleID, Modules, newvalue)

# before we can join the two dfs with rbind must change from tbl dataframe caused by dplyr
plot <- as.data.frame(plot)
other <- as.data.frame(other)

# join for plotting
plot <- as.data.frame(rbind(plot,other))


# merge with map to get day variable
plot <- merge(plot, map, by = "X.SampleID")

set.seed(1)

# get right number of colors for plotting
no_cols <- length(unique(plot$Modules))
#colors_func <- sample(cols_func(no_cols))
colors_func <- sample(c(pal,pal4), no_cols)

# order participants by their microbiome diversity
# reorder by ordered factor
plot$UserName <- gsub("MCTs", "", plot$UserName)
ord_factor <- gsub("MCTs", "", ord_factor)
plot$UserName <- factor(plot$UserName, levels = ord_factor)

# reorder modules
mod_ord_factor <- c("Other", mod_ord_factor)

plot$Modules <- as.factor(plot$Modules)
plot$Modules <-factor(plot$Modules, levels = mod_ord_factor)


# make the plot2
func_plot <- ggplot(data = plot, aes(x=StudyDayNo, y = newvalue, fill=Modules)) +
  geom_area(stat = "identity") +
  facet_grid(.~UserName, scales = "free") +
  scale_fill_manual(values = colors_func) +
  scale_x_discrete(drop = FALSE) +
  theme_classic() +
  theme(strip.text.x = element_text(angle = 0, size = 6, face = "italic"),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(size = 9),
        axis.title = element_text(size = 9),
        plot.title = element_text(hjust = 0.5),
        axis.title.x = element_blank(),
        strip.background = element_rect(color = "grey"), 
        legend.position = "bottom",
        legend.text = element_text(size = 6),
        legend.title = element_blank(),
        panel.spacing.x=unit(0.05, "lines")) +
  guides(fill = guide_legend(reverse = FALSE, 
                             keywidth = 0.5, 
                             keyheight = 0.5, 
                             ncol = 2)) +
                             #nrow = 2)) +
  ylab("Relative Abundance") 

func_plot


```

