---
title: "Procrustes"
author: "Abby"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
always_allow_html: yes
---


```{r setup, include=FALSE, message = FALSE}

require(rmarkdown)
require(knitr)
require(tidyverse)
require(stringr)
require(dplyr)
require(reshape2)
require(zoo)
require(RColorBrewer)


opts_knit$set(root.dir = "/Users/abby/Documents/Projects/dietstudy/")
opts_chunk$set(echo = TRUE, fig.path = "Figs/", dev = c("png", "pdf"), dpi = 300)

```

```{r load long map, echo = FALSE}
map_sample <- read.table("data/maps/SampleID_map.txt", sep = "\t", header = T, comment = "")
map_username <- read.table("data/maps/UserName_map.txt", sep = "\t", header = T, comment = "")

map_sample$StudyDate <- as.Date.factor(map_sample$StudyDate, format = "%m/%d/%y")

```

```{r import 1 day pvals, echo = F}
day1 <- read.table("figures/figure 4/procrustes/results_username_offset_1day/totals.txt", comment = "#", header = F, sep = "\t")
colnames(day1) <- c("FP1","FP2","Num included dimensions", "day1Monte Carlo p-value", "Count better", "M^2")
day1$UserName <- gsub("\\_.*", "", day1$FP1)
day1 <- day1 %>% select(UserName, `day1Monte Carlo p-value`)

map_username <- full_join(map_username, day1)

day2 <- read.table("figures/figure 4/procrustes/results_username_offset_2day/totals.txt", comment = "#", header = F, sep = "\t")
colnames(day2) <- c("FP1","FP2","Num included dimensions", "day2Monte Carlo p-value", "Count better", "M^2")
day2$UserName <- gsub("\\_.*", "", day2$FP1)
day2 <- day2 %>% select(UserName, `day2Monte Carlo p-value`)

map_username <- full_join(map_username, day2)

day3 <- read.table("figures/figure 4/procrustes/results_username_offset_3day/totals.txt", comment = "#", header = F, sep = "\t")
colnames(day3) <- c("FP1","FP2","Num included dimensions", "day3Monte Carlo p-value", "Count better", "M^2")
day3$UserName <- gsub("\\_.*", "", day3$FP1)
day3 <- day3 %>% select(UserName, `day3Monte Carlo p-value`)

map_username <- full_join(map_username, day3)

day4 <- read.table("figures/figure 4/procrustes/results_username_offset_4day/totals.txt", comment = "#", header = F, sep = "\t")
colnames(day4) <- c("FP1","FP2","Num included dimensions", "day4Monte Carlo p-value", "Count better", "M^2")
day4$UserName <- gsub("\\_.*", "", day4$FP1)
day4 <- day4 %>% select(UserName, `day4Monte Carlo p-value`)

map_username <- full_join(map_username, day4)

day5 <- read.table("figures/figure 4/procrustes/results_username_offset_5day/totals.txt", comment = "#", header = F, sep = "\t")
colnames(day5) <- c("FP1","FP2","Num included dimensions", "day5Monte Carlo p-value", "Count better", "M^2")
day5$UserName <- gsub("\\_.*", "", day5$FP1)
day5 <- day5 %>% select(UserName, `day5Monte Carlo p-value`)

map_username <- full_join(map_username, day5)

```

```{r pvals_boxplot_offset_days, echo = F, fig.width=7, fig.height = 4}
plot <- map_username
#colnames(plot)[1] <- "UserName"
plot$UserName <- gsub("MCTs", "", plot$UserName)         # remove MCTs from naming
plot <- plot[order(plot$`day1Monte Carlo p-value`),]     # reorder by variable of choice
#plot$UserName <- factor(plot$UserName, levels = plot$UserName)


plot <- plot %>% select(UserName, 
                        `day1Monte Carlo p-value`,
                        `day2Monte Carlo p-value`,
                        `day3Monte Carlo p-value`, 
                        `day4Monte Carlo p-value`,
                        `day5Monte Carlo p-value`)

plot_melt <- melt(plot)
plot_melt <- na.omit(plot_melt)

cols <- brewer.pal(8, "Accent")
cols2 <- colorRampPalette(cols)
mycolors <- sample(cols2(length(unique(plot_melt$UserName))))

ggplot(plot_melt, aes(x = variable, y = value)) +
  geom_boxplot(outlier.shape = NA) + 
  scale_x_discrete(labels = c("1", "2", "3", "4", "5")) +
  geom_jitter(aes(fill = UserName), width = 0.2,shape = 21, fill="light grey", size = 2) +
  #scale_fill_manual(values = mycolors) +
  geom_hline(yintercept = 0.05, linetype = 2, color = "darkgrey") +
  theme_classic() +
  xlab(label = "Offset Diet") +
  ylab(label = "Monte-carlo p-value")


ggplot(plot_melt, aes(x = variable, y = value)) +
  geom_boxplot(outlier.shape = NA) + 
  scale_x_discrete(labels = c("1", "2", "3", "4", "5")) +
  geom_line(aes(group = UserName), color = "grey") +
  geom_point(aes(fill = UserName), width = 0.2,shape = 21, fill = "light grey", size = 2) +
  #scale_fill_manual(values = mycolors) +
  geom_hline(yintercept = 0.05, linetype = 2, color = "darkgrey") +
  theme_classic() +
  xlab(label = "Diet offset (days)") +
  ylab(label = "Monte-carlo p-value")

```


```{r pvals_scatter_offset_days, echo=F, fig.height = 4, fig.width = 4}
# plot <- plot[order(plot$`day2Monte Carlo p-value`),]     # reorder by variable of choice
# #plot$UserName <- factor(plot$UserName, levels = plot$UserName)
# 
# plot <- plot %>% select(UserName, 
#                         `day2Monte Carlo p-value`,
#                         `day3Monte Carlo p-value`)
# 
# plot_melt <- melt(plot)
# plot_melt <- na.omit(plot_melt)
# 
# # Make scatterplot of best v. 1 day, ordered by best
# ggplot(plot_melt, aes(x = UserName, y = log(value), group = variable)) + 
#   geom_point(aes(color = variable), size = 3) +
#   geom_point(shape = 1, size =3, color = "black") +
#   scale_color_manual(values = brewer.pal(2, "Dark2"), labels=c("2 day","3 day")) +
#   #scale_color_manual(values = brewer.pal(5, "Dark2")) +
#   geom_hline(yintercept = log(0.05), linetype = 2, color = "darkgrey") +
#   theme_bw() +
#   theme(axis.text.x = element_text(size = 4),
#         legend.position = c(0.88,0.13),
#         legend.title = element_blank())+
#   xlab(label = "Subject") +
#   ylab(label = "log(Monte Carlo p-value)") +
#   annotate("text", label = "p = 0.05", size = 3, x = 29, y = log(0.04)) 
# 
# 


```
